//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", ConfigurationName="ServiceReference1.DataExchange_Port")]
    public interface DataExchange_Port
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/DataExchange:ImportItemPrices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.ImportItemPrices_Result> ImportItemPricesAsync(ServiceReference1.ImportItemPrices request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/DataExchange:ImportClientPrices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.ImportClientPrices_Result> ImportClientPricesAsync(ServiceReference1.ImportClientPrices request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/DataExchange:SetupClientDiscounts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.SetupClientDiscounts_Result> SetupClientDiscountsAsync(ServiceReference1.SetupClientDiscounts request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/DataExchange:GetClients", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.GetClients_Result> GetClientsAsync(ServiceReference1.GetClients request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/DataExchange:GetSales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.GetSales_Result> GetSalesAsync(ServiceReference1.GetSales request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/DataExchange:GetStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.GetStock_Result> GetStockAsync(ServiceReference1.GetStock request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/DataExchange:GetItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.GetItems_Result> GetItemsAsync(ServiceReference1.GetItems request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ItemPrices
    {
        
        private ItemEntry[] itemEntryField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemEntry", Order=0)]
        public ItemEntry[] ItemEntry
        {
            get
            {
                return this.itemEntryField;
            }
            set
            {
                this.itemEntryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ItemEntry
    {
        
        private string productIDField;
        
        private decimal catalogPriceField;
        
        private decimal catalogPriceInclVATField;
        
        private decimal vATRateField;
        
        private System.DateTime startingDateField;
        
        public ItemEntry()
        {
            this.catalogPriceField = ((decimal)(0.00m));
            this.catalogPriceInclVATField = ((decimal)(0.00m));
            this.vATRateField = ((decimal)(0.00m));
            this.startingDateField = new System.DateTime(0);
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal CatalogPrice
        {
            get
            {
                return this.catalogPriceField;
            }
            set
            {
                this.catalogPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal CatalogPriceInclVAT
        {
            get
            {
                return this.catalogPriceInclVATField;
            }
            set
            {
                this.catalogPriceInclVATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal VATRate
        {
            get
            {
                return this.vATRateField;
            }
            set
            {
                this.vATRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime StartingDate
        {
            get
            {
                return this.startingDateField;
            }
            set
            {
                this.startingDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class Item
    {
        
        private string productIDField;
        
        private string variantCodeField;
        
        private string fullDescriptionField;
        
        private string vendorItemNoField;
        
        private bool blockedField;
        
        public Item()
        {
            this.blockedField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VariantCode
        {
            get
            {
                return this.variantCodeField;
            }
            set
            {
                this.variantCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FullDescription
        {
            get
            {
                return this.fullDescriptionField;
            }
            set
            {
                this.fullDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string VendorItemNo
        {
            get
            {
                return this.vendorItemNoField;
            }
            set
            {
                this.vendorItemNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool Blocked
        {
            get
            {
                return this.blockedField;
            }
            set
            {
                this.blockedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ItemList
    {
        
        private Item[] itemField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Order=0)]
        public Item[] Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class StockTO
    {
        
        private string batchIdField;
        
        private string batchNoField;
        
        private System.DateTime expirationField;
        
        private string productIdField;
        
        private decimal stockLevelField;
        
        public StockTO()
        {
            this.expirationField = new System.DateTime(0);
            this.stockLevelField = ((decimal)(0.00m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string batchId
        {
            get
            {
                return this.batchIdField;
            }
            set
            {
                this.batchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string batchNo
        {
            get
            {
                return this.batchNoField;
            }
            set
            {
                this.batchNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime expiration
        {
            get
            {
                return this.expirationField;
            }
            set
            {
                this.expirationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal stockLevel
        {
            get
            {
                return this.stockLevelField;
            }
            set
            {
                this.stockLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class StockList
    {
        
        private StockTO[] stockTOField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StockTO", Order=0)]
        public StockTO[] StockTO
        {
            get
            {
                return this.stockTOField;
            }
            set
            {
                this.stockTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class SalesEntry
    {
        
        private string productIDField;
        
        private string productNameField;
        
        private string clientMasterIDField;
        
        private string clientIDField;
        
        private string clientNameField;
        
        private string clientName2Field;
        
        private string clientAddressField;
        
        private string clientAddress2Field;
        
        private string clientCityField;
        
        private string clientZIPField;
        
        private string clientRegNoField;
        
        private decimal quantityField;
        
        private decimal basePriceField;
        
        private System.DateTime deliveryDateField;
        
        private bool rebateField;
        
        private string orderNoField;
        
        public SalesEntry()
        {
            this.quantityField = ((decimal)(0.00m));
            this.basePriceField = ((decimal)(0.00m));
            this.deliveryDateField = new System.DateTime(0);
            this.rebateField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProductName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ClientMasterID
        {
            get
            {
                return this.clientMasterIDField;
            }
            set
            {
                this.clientMasterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ClientID
        {
            get
            {
                return this.clientIDField;
            }
            set
            {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ClientName
        {
            get
            {
                return this.clientNameField;
            }
            set
            {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ClientName2
        {
            get
            {
                return this.clientName2Field;
            }
            set
            {
                this.clientName2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ClientAddress
        {
            get
            {
                return this.clientAddressField;
            }
            set
            {
                this.clientAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ClientAddress2
        {
            get
            {
                return this.clientAddress2Field;
            }
            set
            {
                this.clientAddress2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ClientCity
        {
            get
            {
                return this.clientCityField;
            }
            set
            {
                this.clientCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ClientZIP
        {
            get
            {
                return this.clientZIPField;
            }
            set
            {
                this.clientZIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ClientRegNo
        {
            get
            {
                return this.clientRegNoField;
            }
            set
            {
                this.clientRegNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal BasePrice
        {
            get
            {
                return this.basePriceField;
            }
            set
            {
                this.basePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=13)]
        public System.DateTime DeliveryDate
        {
            get
            {
                return this.deliveryDateField;
            }
            set
            {
                this.deliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool Rebate
        {
            get
            {
                return this.rebateField;
            }
            set
            {
                this.rebateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string OrderNo
        {
            get
            {
                return this.orderNoField;
            }
            set
            {
                this.orderNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class SalesList
    {
        
        private SalesEntry[] salesEntryField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesEntry", Order=0)]
        public SalesEntry[] SalesEntry
        {
            get
            {
                return this.salesEntryField;
            }
            set
            {
                this.salesEntryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ClientLine
    {
        
        private string clientMasterIdField;
        
        private string clientIdField;
        
        private string nameField;
        
        private string name2Field;
        
        private string addressField;
        
        private string address2Field;
        
        private string cityField;
        
        private string zipCodeField;
        
        private string regNoField;
        
        private string regNameField;
        
        private bool canceledField;
        
        private string previousMasterIdField;
        
        public ClientLine()
        {
            this.canceledField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ClientMasterId
        {
            get
            {
                return this.clientMasterIdField;
            }
            set
            {
                this.clientMasterIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ClientId
        {
            get
            {
                return this.clientIdField;
            }
            set
            {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name2
        {
            get
            {
                return this.name2Field;
            }
            set
            {
                this.name2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string RegNo
        {
            get
            {
                return this.regNoField;
            }
            set
            {
                this.regNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string RegName
        {
            get
            {
                return this.regNameField;
            }
            set
            {
                this.regNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool Canceled
        {
            get
            {
                return this.canceledField;
            }
            set
            {
                this.canceledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PreviousMasterId
        {
            get
            {
                return this.previousMasterIdField;
            }
            set
            {
                this.previousMasterIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ClientList
    {
        
        private ClientLine[] clientLineField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClientLine", Order=0)]
        public ClientLine[] ClientLine
        {
            get
            {
                return this.clientLineField;
            }
            set
            {
                this.clientLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ClientEntryError
    {
        
        private string clientMasterIDField;
        
        private string productIDField;
        
        private decimal clientPriceField;
        
        private decimal clientPriceInclVATField;
        
        private decimal clientDiscountField;
        
        private System.DateTime startingDateField;
        
        private string errorCodeField;
        
        private string errorTextField;
        
        public ClientEntryError()
        {
            this.clientPriceField = ((decimal)(0.00m));
            this.clientPriceInclVATField = ((decimal)(0.00m));
            this.clientDiscountField = ((decimal)(0.00m));
            this.startingDateField = new System.DateTime(0);
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ClientMasterID
        {
            get
            {
                return this.clientMasterIDField;
            }
            set
            {
                this.clientMasterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal ClientPrice
        {
            get
            {
                return this.clientPriceField;
            }
            set
            {
                this.clientPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal ClientPriceInclVAT
        {
            get
            {
                return this.clientPriceInclVATField;
            }
            set
            {
                this.clientPriceInclVATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal ClientDiscount
        {
            get
            {
                return this.clientDiscountField;
            }
            set
            {
                this.clientDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime StartingDate
        {
            get
            {
                return this.startingDateField;
            }
            set
            {
                this.startingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ErrorText
        {
            get
            {
                return this.errorTextField;
            }
            set
            {
                this.errorTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ClientPriceErrors
    {
        
        private ClientEntryError[] clientEntryErrorField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClientEntryError", Order=0)]
        public ClientEntryError[] ClientEntryError
        {
            get
            {
                return this.clientEntryErrorField;
            }
            set
            {
                this.clientEntryErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ClientEntry
    {
        
        private string clientMasterIDField;
        
        private string productIDField;
        
        private decimal clientPriceField;
        
        private decimal clientPriceInclVATField;
        
        private decimal clientDiscountField;
        
        private System.DateTime startingDateField;
        
        public ClientEntry()
        {
            this.clientPriceField = ((decimal)(0.00m));
            this.clientPriceInclVATField = ((decimal)(0.00m));
            this.clientDiscountField = ((decimal)(0.00m));
            this.startingDateField = new System.DateTime(0);
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ClientMasterID
        {
            get
            {
                return this.clientMasterIDField;
            }
            set
            {
                this.clientMasterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal ClientPrice
        {
            get
            {
                return this.clientPriceField;
            }
            set
            {
                this.clientPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal ClientPriceInclVAT
        {
            get
            {
                return this.clientPriceInclVATField;
            }
            set
            {
                this.clientPriceInclVATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal ClientDiscount
        {
            get
            {
                return this.clientDiscountField;
            }
            set
            {
                this.clientDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime StartingDate
        {
            get
            {
                return this.startingDateField;
            }
            set
            {
                this.startingDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ClientPrices
    {
        
        private ClientEntry[] clientEntryField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClientEntry", Order=0)]
        public ClientEntry[] ClientEntry
        {
            get
            {
                return this.clientEntryField;
            }
            set
            {
                this.clientEntryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ItemEntryError
    {
        
        private string productIDField;
        
        private decimal catalogPriceField;
        
        private decimal catalogPriceInclVATField;
        
        private decimal vATRateField;
        
        private System.DateTime startingDateField;
        
        private string errorCodeField;
        
        private string errorTextField;
        
        public ItemEntryError()
        {
            this.catalogPriceField = ((decimal)(0.00m));
            this.catalogPriceInclVATField = ((decimal)(0.00m));
            this.vATRateField = ((decimal)(0.00m));
            this.startingDateField = new System.DateTime(0);
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal CatalogPrice
        {
            get
            {
                return this.catalogPriceField;
            }
            set
            {
                this.catalogPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal CatalogPriceInclVAT
        {
            get
            {
                return this.catalogPriceInclVATField;
            }
            set
            {
                this.catalogPriceInclVATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal VATRate
        {
            get
            {
                return this.vATRateField;
            }
            set
            {
                this.vATRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime StartingDate
        {
            get
            {
                return this.startingDateField;
            }
            set
            {
                this.startingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ErrorText
        {
            get
            {
                return this.errorTextField;
            }
            set
            {
                this.errorTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ItemPriceErrors
    {
        
        private ItemEntryError[] itemEntryErrorField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemEntryError", Order=0)]
        public ItemEntryError[] ItemEntryError
        {
            get
            {
                return this.itemEntryErrorField;
            }
            set
            {
                this.itemEntryErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportItemPrices", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", IsWrapped=true)]
    public partial class ImportItemPrices
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=0)]
        public string listID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=1)]
        public ServiceReference1.ItemPrices itemPriceList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=2)]
        public int returnLinesPassedCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=3)]
        public int returnLinesErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=4)]
        public int returnErrorCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=5)]
        public string returnErrorText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=6)]
        public ServiceReference1.ItemPriceErrors returnItemErrorList;
        
        public ImportItemPrices()
        {
        }
        
        public ImportItemPrices(string listID, ServiceReference1.ItemPrices itemPriceList, int returnLinesPassedCount, int returnLinesErrorCount, int returnErrorCode, string returnErrorText, ServiceReference1.ItemPriceErrors returnItemErrorList)
        {
            this.listID = listID;
            this.itemPriceList = itemPriceList;
            this.returnLinesPassedCount = returnLinesPassedCount;
            this.returnLinesErrorCount = returnLinesErrorCount;
            this.returnErrorCode = returnErrorCode;
            this.returnErrorText = returnErrorText;
            this.returnItemErrorList = returnItemErrorList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportItemPrices_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", IsWrapped=true)]
    public partial class ImportItemPrices_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=0)]
        public int returnLinesPassedCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=1)]
        public int returnLinesErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=2)]
        public int returnErrorCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=3)]
        public string returnErrorText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=4)]
        public ServiceReference1.ItemPriceErrors returnItemErrorList;
        
        public ImportItemPrices_Result()
        {
        }
        
        public ImportItemPrices_Result(int returnLinesPassedCount, int returnLinesErrorCount, int returnErrorCode, string returnErrorText, ServiceReference1.ItemPriceErrors returnItemErrorList)
        {
            this.returnLinesPassedCount = returnLinesPassedCount;
            this.returnLinesErrorCount = returnLinesErrorCount;
            this.returnErrorCode = returnErrorCode;
            this.returnErrorText = returnErrorText;
            this.returnItemErrorList = returnItemErrorList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportClientPrices", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", IsWrapped=true)]
    public partial class ImportClientPrices
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=0)]
        public string listID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=1)]
        public ServiceReference1.ClientPrices clientPriceList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=2)]
        public int returnLinesPassedCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=3)]
        public int returnLinesErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=4)]
        public int returnErrorCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=5)]
        public string returnErrorText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=6)]
        public ServiceReference1.ClientPriceErrors returnClientErrorList;
        
        public ImportClientPrices()
        {
        }
        
        public ImportClientPrices(string listID, ServiceReference1.ClientPrices clientPriceList, int returnLinesPassedCount, int returnLinesErrorCount, int returnErrorCode, string returnErrorText, ServiceReference1.ClientPriceErrors returnClientErrorList)
        {
            this.listID = listID;
            this.clientPriceList = clientPriceList;
            this.returnLinesPassedCount = returnLinesPassedCount;
            this.returnLinesErrorCount = returnLinesErrorCount;
            this.returnErrorCode = returnErrorCode;
            this.returnErrorText = returnErrorText;
            this.returnClientErrorList = returnClientErrorList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportClientPrices_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", IsWrapped=true)]
    public partial class ImportClientPrices_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=0)]
        public int returnLinesPassedCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=1)]
        public int returnLinesErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=2)]
        public int returnErrorCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=3)]
        public string returnErrorText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=4)]
        public ServiceReference1.ClientPriceErrors returnClientErrorList;
        
        public ImportClientPrices_Result()
        {
        }
        
        public ImportClientPrices_Result(int returnLinesPassedCount, int returnLinesErrorCount, int returnErrorCode, string returnErrorText, ServiceReference1.ClientPriceErrors returnClientErrorList)
        {
            this.returnLinesPassedCount = returnLinesPassedCount;
            this.returnLinesErrorCount = returnLinesErrorCount;
            this.returnErrorCode = returnErrorCode;
            this.returnErrorText = returnErrorText;
            this.returnClientErrorList = returnClientErrorList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetupClientDiscounts", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", IsWrapped=true)]
    public partial class SetupClientDiscounts
    {
        
        public SetupClientDiscounts()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetupClientDiscounts_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", IsWrapped=true)]
    public partial class SetupClientDiscounts_Result
    {
        
        public SetupClientDiscounts_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClients", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", IsWrapped=true)]
    public partial class GetClients
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=0)]
        public string listID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=1)]
        public ServiceReference1.ClientList returnClients;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=2)]
        public int returnErrorCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=3)]
        public string returnErrorText;
        
        public GetClients()
        {
        }
        
        public GetClients(string listID, ServiceReference1.ClientList returnClients, int returnErrorCode, string returnErrorText)
        {
            this.listID = listID;
            this.returnClients = returnClients;
            this.returnErrorCode = returnErrorCode;
            this.returnErrorText = returnErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClients_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", IsWrapped=true)]
    public partial class GetClients_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=0)]
        public ServiceReference1.ClientList returnClients;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=1)]
        public int returnErrorCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=2)]
        public string returnErrorText;
        
        public GetClients_Result()
        {
        }
        
        public GetClients_Result(ServiceReference1.ClientList returnClients, int returnErrorCode, string returnErrorText)
        {
            this.returnClients = returnClients;
            this.returnErrorCode = returnErrorCode;
            this.returnErrorText = returnErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSales", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", IsWrapped=true)]
    public partial class GetSales
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=0)]
        public string listID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime startingDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime endingDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=3)]
        public ServiceReference1.SalesList returnSalesList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=4)]
        public int returnErrorCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=5)]
        public string returnErrorText;
        
        public GetSales()
        {
        }
        
        public GetSales(string listID, System.DateTime startingDate, System.DateTime endingDate, ServiceReference1.SalesList returnSalesList, int returnErrorCode, string returnErrorText)
        {
            this.listID = listID;
            this.startingDate = startingDate;
            this.endingDate = endingDate;
            this.returnSalesList = returnSalesList;
            this.returnErrorCode = returnErrorCode;
            this.returnErrorText = returnErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSales_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", IsWrapped=true)]
    public partial class GetSales_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=0)]
        public ServiceReference1.SalesList returnSalesList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=1)]
        public int returnErrorCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=2)]
        public string returnErrorText;
        
        public GetSales_Result()
        {
        }
        
        public GetSales_Result(ServiceReference1.SalesList returnSalesList, int returnErrorCode, string returnErrorText)
        {
            this.returnSalesList = returnSalesList;
            this.returnErrorCode = returnErrorCode;
            this.returnErrorText = returnErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStock", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", IsWrapped=true)]
    public partial class GetStock
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=0)]
        public string listID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=1)]
        public ServiceReference1.StockList returnStock;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=2)]
        public int returnErrorCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=3)]
        public string returnErrorText;
        
        public GetStock()
        {
        }
        
        public GetStock(string listID, ServiceReference1.StockList returnStock, int returnErrorCode, string returnErrorText)
        {
            this.listID = listID;
            this.returnStock = returnStock;
            this.returnErrorCode = returnErrorCode;
            this.returnErrorText = returnErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStock_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", IsWrapped=true)]
    public partial class GetStock_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=0)]
        public ServiceReference1.StockList returnStock;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=1)]
        public int returnErrorCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=2)]
        public string returnErrorText;
        
        public GetStock_Result()
        {
        }
        
        public GetStock_Result(ServiceReference1.StockList returnStock, int returnErrorCode, string returnErrorText)
        {
            this.returnStock = returnStock;
            this.returnErrorCode = returnErrorCode;
            this.returnErrorText = returnErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetItems", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", IsWrapped=true)]
    public partial class GetItems
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=0)]
        public string listID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=1)]
        public ServiceReference1.ItemList returnItems;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=2)]
        public int returnErrorCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=3)]
        public string returnErrorText;
        
        public GetItems()
        {
        }
        
        public GetItems(string listID, ServiceReference1.ItemList returnItems, int returnErrorCode, string returnErrorText)
        {
            this.listID = listID;
            this.returnItems = returnItems;
            this.returnErrorCode = returnErrorCode;
            this.returnErrorText = returnErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetItems_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", IsWrapped=true)]
    public partial class GetItems_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=0)]
        public ServiceReference1.ItemList returnItems;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=1)]
        public int returnErrorCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DataExchange", Order=2)]
        public string returnErrorText;
        
        public GetItems_Result()
        {
        }
        
        public GetItems_Result(ServiceReference1.ItemList returnItems, int returnErrorCode, string returnErrorText)
        {
            this.returnItems = returnItems;
            this.returnErrorCode = returnErrorCode;
            this.returnErrorText = returnErrorText;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface DataExchange_PortChannel : ServiceReference1.DataExchange_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class DataExchange_PortClient : System.ServiceModel.ClientBase<ServiceReference1.DataExchange_Port>, ServiceReference1.DataExchange_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DataExchange_PortClient() : 
                base(DataExchange_PortClient.GetDefaultBinding(), DataExchange_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DataExchange_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataExchange_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(DataExchange_PortClient.GetBindingForEndpoint(endpointConfiguration), DataExchange_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataExchange_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DataExchange_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataExchange_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DataExchange_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataExchange_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ImportItemPrices_Result> ImportItemPricesAsync(ServiceReference1.ImportItemPrices request)
        {
            return base.Channel.ImportItemPricesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ImportClientPrices_Result> ImportClientPricesAsync(ServiceReference1.ImportClientPrices request)
        {
            return base.Channel.ImportClientPricesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.SetupClientDiscounts_Result> ServiceReference1.DataExchange_Port.SetupClientDiscountsAsync(ServiceReference1.SetupClientDiscounts request)
        {
            return base.Channel.SetupClientDiscountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SetupClientDiscounts_Result> SetupClientDiscountsAsync()
        {
            ServiceReference1.SetupClientDiscounts inValue = new ServiceReference1.SetupClientDiscounts();
            return ((ServiceReference1.DataExchange_Port)(this)).SetupClientDiscountsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetClients_Result> GetClientsAsync(ServiceReference1.GetClients request)
        {
            return base.Channel.GetClientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetSales_Result> GetSalesAsync(ServiceReference1.GetSales request)
        {
            return base.Channel.GetSalesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetStock_Result> GetStockAsync(ServiceReference1.GetStock request)
        {
            return base.Channel.GetStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetItems_Result> GetItemsAsync(ServiceReference1.GetItems request)
        {
            return base.Channel.GetItemsAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataExchange_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataExchange_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://ws.samohyl.cz:7783/ws/WS/SAMOHYL/Codeunit/DataExchange");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DataExchange_PortClient.GetBindingForEndpoint(EndpointConfiguration.DataExchange_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DataExchange_PortClient.GetEndpointAddress(EndpointConfiguration.DataExchange_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            DataExchange_Port,
        }
    }
}
