//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacopola.SK.Service
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", ConfigurationName="Pharmacopola.SK.Service.IVendor_Port")]
    public interface IVendor_Port
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Vendor/IVendor_Port/ImportItemPrices", ReplyAction="urn:microsoft-dynamics-schemas/codeunit/Vendor/IVendor_Port/ImportItemPricesRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Pharmacopola.SK.Service.ImportItemPrices_Result> ImportItemPricesAsync(Pharmacopola.SK.Service.ImportItemPrices request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Vendor/IVendor_Port/ImportClientPrices", ReplyAction="urn:microsoft-dynamics-schemas/codeunit/Vendor/IVendor_Port/ImportClientPricesRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Pharmacopola.SK.Service.ImportClientPrices_Result> ImportClientPricesAsync(Pharmacopola.SK.Service.ImportClientPrices request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Vendor/IVendor_Port/GetClients", ReplyAction="urn:microsoft-dynamics-schemas/codeunit/Vendor/IVendor_Port/GetClientsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Pharmacopola.SK.Service.GetClients_Result> GetClientsAsync(Pharmacopola.SK.Service.GetClients request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Vendor/IVendor_Port/GetSales", ReplyAction="urn:microsoft-dynamics-schemas/codeunit/Vendor/IVendor_Port/GetSalesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Pharmacopola.SK.Service.GetSales_Result> GetSalesAsync(Pharmacopola.SK.Service.GetSales request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Vendor/IVendor_Port/GetStock", ReplyAction="urn:microsoft-dynamics-schemas/codeunit/Vendor/IVendor_Port/GetStockResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Pharmacopola.SK.Service.GetStock_Result> GetStockAsync(Pharmacopola.SK.Service.GetStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Vendor/IVendor_Port/GetProducts", ReplyAction="urn:microsoft-dynamics-schemas/codeunit/Vendor/IVendor_Port/GetProductsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Pharmacopola.SK.Service.GetProducts_Result> GetProductsAsync(Pharmacopola.SK.Service.GetProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Vendor/IVendor_Port/GetClientPrices", ReplyAction="urn:microsoft-dynamics-schemas/codeunit/Vendor/IVendor_Port/GetClientPricesRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Pharmacopola.SK.Service.GetClientPrices_Result> GetClientPricesAsync(Pharmacopola.SK.Service.GetClientPrices request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ItemPrices
    {
        
        private ItemEntry[] itemEntryField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemEntry", Order=0)]
        public ItemEntry[] ItemEntry
        {
            get
            {
                return this.itemEntryField;
            }
            set
            {
                this.itemEntryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ItemEntry
    {
        
        private string productIDField;
        
        private decimal catalogPriceField;
        
        private decimal catalogPriceInclVATField;
        
        private decimal vATRateField;
        
        private System.DateTime startingDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal CatalogPrice
        {
            get
            {
                return this.catalogPriceField;
            }
            set
            {
                this.catalogPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal CatalogPriceInclVAT
        {
            get
            {
                return this.catalogPriceInclVATField;
            }
            set
            {
                this.catalogPriceInclVATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal VATRate
        {
            get
            {
                return this.vATRateField;
            }
            set
            {
                this.vATRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime StartingDate
        {
            get
            {
                return this.startingDateField;
            }
            set
            {
                this.startingDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ClientPricesEntry
    {
        
        private string clientIDField;
        
        private string setExpiryField;
        
        private decimal priceField;
        
        private decimal discountField;
        
        private string productIDField;
        
        private System.DateTime validfromField;
        
        private System.DateTime validtoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientID
        {
            get
            {
                return this.clientIDField;
            }
            set
            {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string setExpiry
        {
            get
            {
                return this.setExpiryField;
            }
            set
            {
                this.setExpiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal discount
        {
            get
            {
                return this.discountField;
            }
            set
            {
                this.discountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string productID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime validfrom
        {
            get
            {
                return this.validfromField;
            }
            set
            {
                this.validfromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime validto
        {
            get
            {
                return this.validtoField;
            }
            set
            {
                this.validtoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ProductEntry
    {
        
        private string productIDField;
        
        private string vendorProductIDField;
        
        private string nameField;
        
        private decimal vATField;
        
        private decimal catalogPriceField;
        
        private string finishedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VendorProductID
        {
            get
            {
                return this.vendorProductIDField;
            }
            set
            {
                this.vendorProductIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal VAT
        {
            get
            {
                return this.vATField;
            }
            set
            {
                this.vATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal CatalogPrice
        {
            get
            {
                return this.catalogPriceField;
            }
            set
            {
                this.catalogPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Finished
        {
            get
            {
                return this.finishedField;
            }
            set
            {
                this.finishedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class StockEntry
    {
        
        private string productIDField;
        
        private string batchNoField;
        
        private System.DateTime expirationField;
        
        private decimal stockLevelField;
        
        private decimal reservedQtyOnStockLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BatchNo
        {
            get
            {
                return this.batchNoField;
            }
            set
            {
                this.batchNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Expiration
        {
            get
            {
                return this.expirationField;
            }
            set
            {
                this.expirationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal StockLevel
        {
            get
            {
                return this.stockLevelField;
            }
            set
            {
                this.stockLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal ReservedQtyOnStockLevel
        {
            get
            {
                return this.reservedQtyOnStockLevelField;
            }
            set
            {
                this.reservedQtyOnStockLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class SalesEntry
    {
        
        private string productIDField;
        
        private string productNameField;
        
        private string clientMasterIDField;
        
        private string clientIDField;
        
        private string clientNameField;
        
        private string clientName2Field;
        
        private string clientAddressField;
        
        private string clientAddress2Field;
        
        private string clientCityField;
        
        private string clientZIPField;
        
        private string clientRegNoField;
        
        private decimal quantityField;
        
        private decimal basePriceField;
        
        private System.DateTime deliveryDateField;
        
        private bool rebateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProductName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ClientMasterID
        {
            get
            {
                return this.clientMasterIDField;
            }
            set
            {
                this.clientMasterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ClientID
        {
            get
            {
                return this.clientIDField;
            }
            set
            {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ClientName
        {
            get
            {
                return this.clientNameField;
            }
            set
            {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ClientName2
        {
            get
            {
                return this.clientName2Field;
            }
            set
            {
                this.clientName2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ClientAddress
        {
            get
            {
                return this.clientAddressField;
            }
            set
            {
                this.clientAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ClientAddress2
        {
            get
            {
                return this.clientAddress2Field;
            }
            set
            {
                this.clientAddress2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ClientCity
        {
            get
            {
                return this.clientCityField;
            }
            set
            {
                this.clientCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ClientZIP
        {
            get
            {
                return this.clientZIPField;
            }
            set
            {
                this.clientZIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ClientRegNo
        {
            get
            {
                return this.clientRegNoField;
            }
            set
            {
                this.clientRegNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal BasePrice
        {
            get
            {
                return this.basePriceField;
            }
            set
            {
                this.basePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=13)]
        public System.DateTime DeliveryDate
        {
            get
            {
                return this.deliveryDateField;
            }
            set
            {
                this.deliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool Rebate
        {
            get
            {
                return this.rebateField;
            }
            set
            {
                this.rebateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class SalesList
    {
        
        private SalesEntry[] salesEntryField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesEntry", Order=0)]
        public SalesEntry[] SalesEntry
        {
            get
            {
                return this.salesEntryField;
            }
            set
            {
                this.salesEntryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ClientLine
    {
        
        private string clientMasterIdField;
        
        private string clientIdField;
        
        private string nameField;
        
        private string name2Field;
        
        private string addressField;
        
        private string address2Field;
        
        private string cityField;
        
        private string zipCodeField;
        
        private string regNoField;
        
        private string regNameField;
        
        private bool canceledField;
        
        private string previousMasterIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ClientMasterId
        {
            get
            {
                return this.clientMasterIdField;
            }
            set
            {
                this.clientMasterIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ClientId
        {
            get
            {
                return this.clientIdField;
            }
            set
            {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name2
        {
            get
            {
                return this.name2Field;
            }
            set
            {
                this.name2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string RegNo
        {
            get
            {
                return this.regNoField;
            }
            set
            {
                this.regNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string RegName
        {
            get
            {
                return this.regNameField;
            }
            set
            {
                this.regNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool Canceled
        {
            get
            {
                return this.canceledField;
            }
            set
            {
                this.canceledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PreviousMasterId
        {
            get
            {
                return this.previousMasterIdField;
            }
            set
            {
                this.previousMasterIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ClientList
    {
        
        private ClientLine[] clientLineField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClientLine", Order=0)]
        public ClientLine[] ClientLine
        {
            get
            {
                return this.clientLineField;
            }
            set
            {
                this.clientLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ClientEntryError
    {
        
        private string clientMasterIDField;
        
        private string productIDField;
        
        private decimal clientPriceField;
        
        private decimal clientPriceInclVATField;
        
        private decimal clientDiscountField;
        
        private System.DateTime startingDateField;
        
        private string errorCodeField;
        
        private string errorTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ClientMasterID
        {
            get
            {
                return this.clientMasterIDField;
            }
            set
            {
                this.clientMasterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal ClientPrice
        {
            get
            {
                return this.clientPriceField;
            }
            set
            {
                this.clientPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal ClientPriceInclVAT
        {
            get
            {
                return this.clientPriceInclVATField;
            }
            set
            {
                this.clientPriceInclVATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal ClientDiscount
        {
            get
            {
                return this.clientDiscountField;
            }
            set
            {
                this.clientDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime StartingDate
        {
            get
            {
                return this.startingDateField;
            }
            set
            {
                this.startingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ErrorText
        {
            get
            {
                return this.errorTextField;
            }
            set
            {
                this.errorTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ClientPriceErrors
    {
        
        private ClientEntryError[] clientEntryErrorField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClientEntryError", Order=0)]
        public ClientEntryError[] ClientEntryError
        {
            get
            {
                return this.clientEntryErrorField;
            }
            set
            {
                this.clientEntryErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ClientEntry
    {
        
        private string clientMasterIDField;
        
        private string productIDField;
        
        private decimal clientPriceField;
        
        private decimal clientPriceInclVATField;
        
        private decimal clientDiscountField;
        
        private System.DateTime startingDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ClientMasterID
        {
            get
            {
                return this.clientMasterIDField;
            }
            set
            {
                this.clientMasterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal ClientPrice
        {
            get
            {
                return this.clientPriceField;
            }
            set
            {
                this.clientPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal ClientPriceInclVAT
        {
            get
            {
                return this.clientPriceInclVATField;
            }
            set
            {
                this.clientPriceInclVATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal ClientDiscount
        {
            get
            {
                return this.clientDiscountField;
            }
            set
            {
                this.clientDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime StartingDate
        {
            get
            {
                return this.startingDateField;
            }
            set
            {
                this.startingDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ClientPrices
    {
        
        private ClientEntry[] clientEntryField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClientEntry", Order=0)]
        public ClientEntry[] ClientEntry
        {
            get
            {
                return this.clientEntryField;
            }
            set
            {
                this.clientEntryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ItemEntryError
    {
        
        private string productIDField;
        
        private decimal catalogPriceField;
        
        private decimal catalogPriceInclVATField;
        
        private decimal vATRateField;
        
        private System.DateTime startingDateField;
        
        private string errorCodeField;
        
        private string errorTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal CatalogPrice
        {
            get
            {
                return this.catalogPriceField;
            }
            set
            {
                this.catalogPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal CatalogPriceInclVAT
        {
            get
            {
                return this.catalogPriceInclVATField;
            }
            set
            {
                this.catalogPriceInclVATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal VATRate
        {
            get
            {
                return this.vATRateField;
            }
            set
            {
                this.vATRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime StartingDate
        {
            get
            {
                return this.startingDateField;
            }
            set
            {
                this.startingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ErrorText
        {
            get
            {
                return this.errorTextField;
            }
            set
            {
                this.errorTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/NAV")]
    public partial class ItemPriceErrors
    {
        
        private ItemEntryError[] itemEntryErrorField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemEntryError", Order=0)]
        public ItemEntryError[] ItemEntryError
        {
            get
            {
                return this.itemEntryErrorField;
            }
            set
            {
                this.itemEntryErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportItemPrices", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", IsWrapped=true)]
    public partial class ImportItemPrices
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=0)]
        public Pharmacopola.SK.Service.ItemPrices itemPriceList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=1)]
        public int returnLinesPassedCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=2)]
        public int returnLinesErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=3)]
        public Pharmacopola.SK.Service.ItemPriceErrors returnItemErrorList;
        
        public ImportItemPrices()
        {
        }
        
        public ImportItemPrices(Pharmacopola.SK.Service.ItemPrices itemPriceList, int returnLinesPassedCount, int returnLinesErrorCount, Pharmacopola.SK.Service.ItemPriceErrors returnItemErrorList)
        {
            this.itemPriceList = itemPriceList;
            this.returnLinesPassedCount = returnLinesPassedCount;
            this.returnLinesErrorCount = returnLinesErrorCount;
            this.returnItemErrorList = returnItemErrorList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportItemPrices_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", IsWrapped=true)]
    public partial class ImportItemPrices_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=0)]
        public int returnLinesPassedCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=1)]
        public int returnLinesErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=2)]
        public Pharmacopola.SK.Service.ItemPriceErrors returnItemErrorList;
        
        public ImportItemPrices_Result()
        {
        }
        
        public ImportItemPrices_Result(int returnLinesPassedCount, int returnLinesErrorCount, Pharmacopola.SK.Service.ItemPriceErrors returnItemErrorList)
        {
            this.returnLinesPassedCount = returnLinesPassedCount;
            this.returnLinesErrorCount = returnLinesErrorCount;
            this.returnItemErrorList = returnItemErrorList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportClientPrices", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", IsWrapped=true)]
    public partial class ImportClientPrices
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=0)]
        public Pharmacopola.SK.Service.ClientPrices clientPriceList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=1)]
        public int returnLinesPassedCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=2)]
        public int returnLinesErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=3)]
        public Pharmacopola.SK.Service.ClientPriceErrors returnClientErrorList;
        
        public ImportClientPrices()
        {
        }
        
        public ImportClientPrices(Pharmacopola.SK.Service.ClientPrices clientPriceList, int returnLinesPassedCount, int returnLinesErrorCount, Pharmacopola.SK.Service.ClientPriceErrors returnClientErrorList)
        {
            this.clientPriceList = clientPriceList;
            this.returnLinesPassedCount = returnLinesPassedCount;
            this.returnLinesErrorCount = returnLinesErrorCount;
            this.returnClientErrorList = returnClientErrorList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportClientPrices_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", IsWrapped=true)]
    public partial class ImportClientPrices_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=0)]
        public int returnLinesPassedCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=1)]
        public int returnLinesErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=2)]
        public Pharmacopola.SK.Service.ClientPriceErrors returnClientErrorList;
        
        public ImportClientPrices_Result()
        {
        }
        
        public ImportClientPrices_Result(int returnLinesPassedCount, int returnLinesErrorCount, Pharmacopola.SK.Service.ClientPriceErrors returnClientErrorList)
        {
            this.returnLinesPassedCount = returnLinesPassedCount;
            this.returnLinesErrorCount = returnLinesErrorCount;
            this.returnClientErrorList = returnClientErrorList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClients", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", IsWrapped=true)]
    public partial class GetClients
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=0)]
        public Pharmacopola.SK.Service.ClientList returnClients;
        
        public GetClients()
        {
        }
        
        public GetClients(Pharmacopola.SK.Service.ClientList returnClients)
        {
            this.returnClients = returnClients;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClients_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", IsWrapped=true)]
    public partial class GetClients_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=0)]
        public Pharmacopola.SK.Service.ClientList returnClients;
        
        public GetClients_Result()
        {
        }
        
        public GetClients_Result(Pharmacopola.SK.Service.ClientList returnClients)
        {
            this.returnClients = returnClients;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSales", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", IsWrapped=true)]
    public partial class GetSales
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime startingDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime endingDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=2)]
        public Pharmacopola.SK.Service.SalesList returnSalesList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=3)]
        public int returnErrorCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=4)]
        public string returnErrorText;
        
        public GetSales()
        {
        }
        
        public GetSales(System.DateTime startingDate, System.DateTime endingDate, Pharmacopola.SK.Service.SalesList returnSalesList, int returnErrorCode, string returnErrorText)
        {
            this.startingDate = startingDate;
            this.endingDate = endingDate;
            this.returnSalesList = returnSalesList;
            this.returnErrorCode = returnErrorCode;
            this.returnErrorText = returnErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSales_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", IsWrapped=true)]
    public partial class GetSales_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=0)]
        public Pharmacopola.SK.Service.SalesList returnSalesList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=1)]
        public int returnErrorCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=2)]
        public string returnErrorText;
        
        public GetSales_Result()
        {
        }
        
        public GetSales_Result(Pharmacopola.SK.Service.SalesList returnSalesList, int returnErrorCode, string returnErrorText)
        {
            this.returnSalesList = returnSalesList;
            this.returnErrorCode = returnErrorCode;
            this.returnErrorText = returnErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockRequest
    {
        
        public GetStockRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStock_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", IsWrapped=true)]
    public partial class GetStock_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("StockLine", Namespace="urn:microsoft-dynamics-nav/xmlports/NAV", IsNullable=false)]
        public Pharmacopola.SK.Service.StockEntry[] returnStockList;
        
        public GetStock_Result()
        {
        }
        
        public GetStock_Result(Pharmacopola.SK.Service.StockEntry[] returnStockList)
        {
            this.returnStockList = returnStockList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsRequest
    {
        
        public GetProductsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProducts_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", IsWrapped=true)]
    public partial class GetProducts_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ProductLine", Namespace="urn:microsoft-dynamics-nav/xmlports/NAV", IsNullable=false)]
        public Pharmacopola.SK.Service.ProductEntry[] returnProductList;
        
        public GetProducts_Result()
        {
        }
        
        public GetProducts_Result(Pharmacopola.SK.Service.ProductEntry[] returnProductList)
        {
            this.returnProductList = returnProductList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientPrices", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", IsWrapped=true)]
    public partial class GetClientPrices
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=0)]
        public string clientId;
        
        public GetClientPrices()
        {
        }
        
        public GetClientPrices(string clientId)
        {
            this.clientId = clientId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientPrices_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", IsWrapped=true)]
    public partial class GetClientPrices_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Vendor", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ClientPriceLine", Namespace="urn:microsoft-dynamics-nav/xmlports/NAV", IsNullable=false)]
        public Pharmacopola.SK.Service.ClientPricesEntry[] returnClientPricesList;
        
        public GetClientPrices_Result()
        {
        }
        
        public GetClientPrices_Result(Pharmacopola.SK.Service.ClientPricesEntry[] returnClientPricesList)
        {
            this.returnClientPricesList = returnClientPricesList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IVendor_PortChannel : Pharmacopola.SK.Service.IVendor_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class Vendor_PortClient : System.ServiceModel.ClientBase<Pharmacopola.SK.Service.IVendor_Port>, Pharmacopola.SK.Service.IVendor_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Vendor_PortClient() : 
                base(Vendor_PortClient.GetDefaultBinding(), Vendor_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.VendorBasicHttpBinding.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Vendor_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(Vendor_PortClient.GetBindingForEndpoint(endpointConfiguration), Vendor_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Vendor_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Vendor_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Vendor_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Vendor_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Vendor_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Pharmacopola.SK.Service.ImportItemPrices_Result> ImportItemPricesAsync(Pharmacopola.SK.Service.ImportItemPrices request)
        {
            return base.Channel.ImportItemPricesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pharmacopola.SK.Service.ImportClientPrices_Result> ImportClientPricesAsync(Pharmacopola.SK.Service.ImportClientPrices request)
        {
            return base.Channel.ImportClientPricesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pharmacopola.SK.Service.GetClients_Result> GetClientsAsync(Pharmacopola.SK.Service.GetClients request)
        {
            return base.Channel.GetClientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pharmacopola.SK.Service.GetSales_Result> GetSalesAsync(Pharmacopola.SK.Service.GetSales request)
        {
            return base.Channel.GetSalesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pharmacopola.SK.Service.GetStock_Result> Pharmacopola.SK.Service.IVendor_Port.GetStockAsync(Pharmacopola.SK.Service.GetStockRequest request)
        {
            return base.Channel.GetStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pharmacopola.SK.Service.GetStock_Result> GetStockAsync()
        {
            Pharmacopola.SK.Service.GetStockRequest inValue = new Pharmacopola.SK.Service.GetStockRequest();
            return ((Pharmacopola.SK.Service.IVendor_Port)(this)).GetStockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pharmacopola.SK.Service.GetProducts_Result> Pharmacopola.SK.Service.IVendor_Port.GetProductsAsync(Pharmacopola.SK.Service.GetProductsRequest request)
        {
            return base.Channel.GetProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pharmacopola.SK.Service.GetProducts_Result> GetProductsAsync()
        {
            Pharmacopola.SK.Service.GetProductsRequest inValue = new Pharmacopola.SK.Service.GetProductsRequest();
            return ((Pharmacopola.SK.Service.IVendor_Port)(this)).GetProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pharmacopola.SK.Service.GetClientPrices_Result> Pharmacopola.SK.Service.IVendor_Port.GetClientPricesAsync(Pharmacopola.SK.Service.GetClientPrices request)
        {
            return base.Channel.GetClientPricesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pharmacopola.SK.Service.GetClientPrices_Result> GetClientPricesAsync(string clientId)
        {
            Pharmacopola.SK.Service.GetClientPrices inValue = new Pharmacopola.SK.Service.GetClientPrices();
            inValue.clientId = clientId;
            return ((Pharmacopola.SK.Service.IVendor_Port)(this)).GetClientPricesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.VendorBasicHttpBinding))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.VendorBasicHttpBinding))
            {
                return new System.ServiceModel.EndpointAddress("https://ws.pharmacopola.sk:7783/vendor/Vendor_Port.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Vendor_PortClient.GetBindingForEndpoint(EndpointConfiguration.VendorBasicHttpBinding);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Vendor_PortClient.GetEndpointAddress(EndpointConfiguration.VendorBasicHttpBinding);
        }
        
        public enum EndpointConfiguration
        {
            
            VendorBasicHttpBinding,
        }
    }
}
