//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medart.SK.Service
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nrsys.sk/ZTOS/Service", ConfigurationName="Medart.SK.Service.ZTOSService")]
    public interface ZTOSService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nrsys.sk/ZTOS/Service/GetClients", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Medart.SK.Service.GetClientsResponse> GetClientsAsync(Medart.SK.Service.GetClientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nrsys.sk/ZTOS/Service/GetProducts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Medart.SK.Service.GetProductsResponse> GetProductsAsync(Medart.SK.Service.GetProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nrsys.sk/ZTOS/Service/GetSales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Medart.SK.Service.GetSalesResponse> GetSalesAsync(Medart.SK.Service.GetSalesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nrsys.sk/ZTOS/Service/GetStocks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Medart.SK.Service.GetStocksResponse> GetStocksAsync(Medart.SK.Service.GetStocksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nrsys.sk/ZTOS/Service/GetOrderConfirmation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Medart.SK.Service.GetOrderConfirmationResponse> GetOrderConfirmationAsync(Medart.SK.Service.GetOrderConfirmationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nrsys.sk/ZTOS/Service/SetCatalogPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Medart.SK.Service.SetCatalogPriceResponse> SetCatalogPriceAsync(Medart.SK.Service.SetCatalogPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nrsys.sk/ZTOS/Service/SetCustomerPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Medart.SK.Service.SetCustomerPriceResponse> SetCustomerPriceAsync(Medart.SK.Service.SetCustomerPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nrsys.sk/ZTOS/Service/SetOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Medart.SK.Service.SetOrderResponse> SetOrderAsync(Medart.SK.Service.SetOrderRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class ZTOSAuth
    {
        
        private string userField;
        
        private string passField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string User
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Pass
        {
            get
            {
                return this.passField;
            }
            set
            {
                this.passField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class SetOrderResp
    {
        
        private Status statusField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StatusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public enum Status
    {
        
        /// <remarks/>
        NONE,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        PROCESSING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class OrderItem
    {
        
        private int productIDField;
        
        private decimal quantityField;
        
        private decimal priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class Order
    {
        
        private int clientIDField;
        
        private string clientOrderIDField;
        
        private string orderDateField;
        
        private string deliveryDateField;
        
        private string noteField;
        
        private OrderItem[] orderItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ClientID
        {
            get
            {
                return this.clientIDField;
            }
            set
            {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ClientOrderID
        {
            get
            {
                return this.clientOrderIDField;
            }
            set
            {
                this.clientOrderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrderDate
        {
            get
            {
                return this.orderDateField;
            }
            set
            {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DeliveryDate
        {
            get
            {
                return this.deliveryDateField;
            }
            set
            {
                this.deliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=5)]
        public OrderItem[] OrderItems
        {
            get
            {
                return this.orderItemsField;
            }
            set
            {
                this.orderItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class SetCustomerPriceResp
    {
        
        private Status statusField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StatusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class ProductPrice
    {
        
        private int productIDField;
        
        private decimal priceField;
        
        private string validFromField;
        
        private string validToField;
        
        private System.Nullable<byte> cancelPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ValidFrom
        {
            get
            {
                return this.validFromField;
            }
            set
            {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ValidTo
        {
            get
            {
                return this.validToField;
            }
            set
            {
                this.validToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<byte> CancelPrice
        {
            get
            {
                return this.cancelPriceField;
            }
            set
            {
                this.cancelPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class CustomerPrice
    {
        
        private int clientIDField;
        
        private ProductPrice[] productPricesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ClientID
        {
            get
            {
                return this.clientIDField;
            }
            set
            {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        public ProductPrice[] ProductPrices
        {
            get
            {
                return this.productPricesField;
            }
            set
            {
                this.productPricesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class SetCatalogPriceResp
    {
        
        private Status statusField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private CatalogPrice[] differentCatalogPricesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StatusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        public CatalogPrice[] DifferentCatalogPrices
        {
            get
            {
                return this.differentCatalogPricesField;
            }
            set
            {
                this.differentCatalogPricesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class CatalogPrice
    {
        
        private int productIDField;
        
        private decimal priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class ConfirmedItem
    {
        
        private int productIDField;
        
        private decimal quantityField;
        
        private decimal confirmedQuantityField;
        
        private string noteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal ConfirmedQuantity
        {
            get
            {
                return this.confirmedQuantityField;
            }
            set
            {
                this.confirmedQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class OrderConfirmation
    {
        
        private int clientIDField;
        
        private string clientOrderIDField;
        
        private string distribOrderNumberField;
        
        private string orderDateField;
        
        private string deliveryDateField;
        
        private string noteField;
        
        private ConfirmedItem[] confirmedItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ClientID
        {
            get
            {
                return this.clientIDField;
            }
            set
            {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ClientOrderID
        {
            get
            {
                return this.clientOrderIDField;
            }
            set
            {
                this.clientOrderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DistribOrderNumber
        {
            get
            {
                return this.distribOrderNumberField;
            }
            set
            {
                this.distribOrderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OrderDate
        {
            get
            {
                return this.orderDateField;
            }
            set
            {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DeliveryDate
        {
            get
            {
                return this.deliveryDateField;
            }
            set
            {
                this.deliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=6)]
        public ConfirmedItem[] ConfirmedItems
        {
            get
            {
                return this.confirmedItemsField;
            }
            set
            {
                this.confirmedItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class GetOrderConfirmationResp
    {
        
        private Status statusField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private OrderConfirmation orderConfirmationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StatusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public OrderConfirmation OrderConfirmation
        {
            get
            {
                return this.orderConfirmationField;
            }
            set
            {
                this.orderConfirmationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class ProductStock
    {
        
        private int productIDField;
        
        private decimal quantityField;
        
        private string expirationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Expiration
        {
            get
            {
                return this.expirationField;
            }
            set
            {
                this.expirationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class BranchStock
    {
        
        private ProductStock[] productStocksField;
        
        private int branchCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        public ProductStock[] ProductStocks
        {
            get
            {
                return this.productStocksField;
            }
            set
            {
                this.productStocksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int BranchCode
        {
            get
            {
                return this.branchCodeField;
            }
            set
            {
                this.branchCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class GetStocksResp
    {
        
        private Status statusField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private BranchStock[] branchStocksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StatusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        public BranchStock[] BranchStocks
        {
            get
            {
                return this.branchStocksField;
            }
            set
            {
                this.branchStocksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class Sale
    {
        
        private int clientIDField;
        
        private string dateOfSaleField;
        
        private int productIDField;
        
        private decimal finalSalePriceField;
        
        private decimal quantityField;
        
        private bool rabatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ClientID
        {
            get
            {
                return this.clientIDField;
            }
            set
            {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DateOfSale
        {
            get
            {
                return this.dateOfSaleField;
            }
            set
            {
                this.dateOfSaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal FinalSalePrice
        {
            get
            {
                return this.finalSalePriceField;
            }
            set
            {
                this.finalSalePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool Rabat
        {
            get
            {
                return this.rabatField;
            }
            set
            {
                this.rabatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class GetSalesResp
    {
        
        private Status statusField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private Sale[] salesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StatusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        public Sale[] Sales
        {
            get
            {
                return this.salesField;
            }
            set
            {
                this.salesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class Product
    {
        
        private int productIDField;
        
        private string nameField;
        
        private decimal catalogPriceField;
        
        private decimal vATField;
        
        private bool activeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal CatalogPrice
        {
            get
            {
                return this.catalogPriceField;
            }
            set
            {
                this.catalogPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal VAT
        {
            get
            {
                return this.vATField;
            }
            set
            {
                this.vATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class GetProductsResp
    {
        
        private Status statusField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private Product[] productsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StatusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        public Product[] Products
        {
            get
            {
                return this.productsField;
            }
            set
            {
                this.productsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class Client
    {
        
        private int clientIDField;
        
        private int branchCodeField;
        
        private string typeField;
        
        private string nameField;
        
        private string streetField;
        
        private string cityField;
        
        private string zipField;
        
        private string iCOField;
        
        private bool activeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ClientID
        {
            get
            {
                return this.clientIDField;
            }
            set
            {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int BranchCode
        {
            get
            {
                return this.branchCodeField;
            }
            set
            {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ICO
        {
            get
            {
                return this.iCOField;
            }
            set
            {
                this.iCOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
    public partial class GetClientsResp
    {
        
        private Status statusField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private Client[] clientsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StatusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        public Client[] Clients
        {
            get
            {
                return this.clientsField;
            }
            set
            {
                this.clientsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClients", WrapperNamespace="http://nrsys.sk/ZTOS/Service/Types", IsWrapped=true)]
    public partial class GetClientsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
        public Medart.SK.Service.ZTOSAuth ZTOSAuth;
        
        public GetClientsRequest()
        {
        }
        
        public GetClientsRequest(Medart.SK.Service.ZTOSAuth ZTOSAuth)
        {
            this.ZTOSAuth = ZTOSAuth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientsResponse", WrapperNamespace="http://nrsys.sk/ZTOS/Service/Types", IsWrapped=true)]
    public partial class GetClientsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types", Order=0)]
        public Medart.SK.Service.GetClientsResp GetClientsResult;
        
        public GetClientsResponse()
        {
        }
        
        public GetClientsResponse(Medart.SK.Service.GetClientsResp GetClientsResult)
        {
            this.GetClientsResult = GetClientsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProducts", WrapperNamespace="http://nrsys.sk/ZTOS/Service/Types", IsWrapped=true)]
    public partial class GetProductsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
        public Medart.SK.Service.ZTOSAuth ZTOSAuth;
        
        public GetProductsRequest()
        {
        }
        
        public GetProductsRequest(Medart.SK.Service.ZTOSAuth ZTOSAuth)
        {
            this.ZTOSAuth = ZTOSAuth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductsResponse", WrapperNamespace="http://nrsys.sk/ZTOS/Service/Types", IsWrapped=true)]
    public partial class GetProductsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types", Order=0)]
        public Medart.SK.Service.GetProductsResp GetProductsResult;
        
        public GetProductsResponse()
        {
        }
        
        public GetProductsResponse(Medart.SK.Service.GetProductsResp GetProductsResult)
        {
            this.GetProductsResult = GetProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSales", WrapperNamespace="http://nrsys.sk/ZTOS/Service/Types", IsWrapped=true)]
    public partial class GetSalesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
        public Medart.SK.Service.ZTOSAuth ZTOSAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types", Order=0)]
        public string DateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types", Order=1)]
        public string DateTo;
        
        public GetSalesRequest()
        {
        }
        
        public GetSalesRequest(Medart.SK.Service.ZTOSAuth ZTOSAuth, string DateFrom, string DateTo)
        {
            this.ZTOSAuth = ZTOSAuth;
            this.DateFrom = DateFrom;
            this.DateTo = DateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSalesResponse", WrapperNamespace="http://nrsys.sk/ZTOS/Service/Types", IsWrapped=true)]
    public partial class GetSalesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types", Order=0)]
        public Medart.SK.Service.GetSalesResp GetSalesResult;
        
        public GetSalesResponse()
        {
        }
        
        public GetSalesResponse(Medart.SK.Service.GetSalesResp GetSalesResult)
        {
            this.GetSalesResult = GetSalesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStocks", WrapperNamespace="http://nrsys.sk/ZTOS/Service/Types", IsWrapped=true)]
    public partial class GetStocksRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
        public Medart.SK.Service.ZTOSAuth ZTOSAuth;
        
        public GetStocksRequest()
        {
        }
        
        public GetStocksRequest(Medart.SK.Service.ZTOSAuth ZTOSAuth)
        {
            this.ZTOSAuth = ZTOSAuth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStocksResponse", WrapperNamespace="http://nrsys.sk/ZTOS/Service/Types", IsWrapped=true)]
    public partial class GetStocksResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types", Order=0)]
        public Medart.SK.Service.GetStocksResp GetStocksResult;
        
        public GetStocksResponse()
        {
        }
        
        public GetStocksResponse(Medart.SK.Service.GetStocksResp GetStocksResult)
        {
            this.GetStocksResult = GetStocksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrderConfirmation", WrapperNamespace="http://nrsys.sk/ZTOS/Service/Types", IsWrapped=true)]
    public partial class GetOrderConfirmationRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
        public Medart.SK.Service.ZTOSAuth ZTOSAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types", Order=0)]
        public int ClientID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types", Order=1)]
        public string ClientOrderID;
        
        public GetOrderConfirmationRequest()
        {
        }
        
        public GetOrderConfirmationRequest(Medart.SK.Service.ZTOSAuth ZTOSAuth, int ClientID, string ClientOrderID)
        {
            this.ZTOSAuth = ZTOSAuth;
            this.ClientID = ClientID;
            this.ClientOrderID = ClientOrderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrderConfirmationResponse", WrapperNamespace="http://nrsys.sk/ZTOS/Service/Types", IsWrapped=true)]
    public partial class GetOrderConfirmationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types", Order=0)]
        public Medart.SK.Service.GetOrderConfirmationResp GetOrderConfirmationResult;
        
        public GetOrderConfirmationResponse()
        {
        }
        
        public GetOrderConfirmationResponse(Medart.SK.Service.GetOrderConfirmationResp GetOrderConfirmationResult)
        {
            this.GetOrderConfirmationResult = GetOrderConfirmationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCatalogPrice", WrapperNamespace="http://nrsys.sk/ZTOS/Service/Types", IsWrapped=true)]
    public partial class SetCatalogPriceRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
        public Medart.SK.Service.ZTOSAuth ZTOSAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types", Order=0)]
        public Medart.SK.Service.CatalogPrice[] CatalogPrices;
        
        public SetCatalogPriceRequest()
        {
        }
        
        public SetCatalogPriceRequest(Medart.SK.Service.ZTOSAuth ZTOSAuth, Medart.SK.Service.CatalogPrice[] CatalogPrices)
        {
            this.ZTOSAuth = ZTOSAuth;
            this.CatalogPrices = CatalogPrices;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCatalogPriceResponse", WrapperNamespace="http://nrsys.sk/ZTOS/Service/Types", IsWrapped=true)]
    public partial class SetCatalogPriceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types", Order=0)]
        public Medart.SK.Service.SetCatalogPriceResp SetCatalogPriceResult;
        
        public SetCatalogPriceResponse()
        {
        }
        
        public SetCatalogPriceResponse(Medart.SK.Service.SetCatalogPriceResp SetCatalogPriceResult)
        {
            this.SetCatalogPriceResult = SetCatalogPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCustomerPrice", WrapperNamespace="http://nrsys.sk/ZTOS/Service/Types", IsWrapped=true)]
    public partial class SetCustomerPriceRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
        public Medart.SK.Service.ZTOSAuth ZTOSAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types", Order=0)]
        public Medart.SK.Service.CustomerPrice[] CustomerPrices;
        
        public SetCustomerPriceRequest()
        {
        }
        
        public SetCustomerPriceRequest(Medart.SK.Service.ZTOSAuth ZTOSAuth, Medart.SK.Service.CustomerPrice[] CustomerPrices)
        {
            this.ZTOSAuth = ZTOSAuth;
            this.CustomerPrices = CustomerPrices;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCustomerPriceResponse", WrapperNamespace="http://nrsys.sk/ZTOS/Service/Types", IsWrapped=true)]
    public partial class SetCustomerPriceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types", Order=0)]
        public Medart.SK.Service.SetCustomerPriceResp SetCustomerPriceResult;
        
        public SetCustomerPriceResponse()
        {
        }
        
        public SetCustomerPriceResponse(Medart.SK.Service.SetCustomerPriceResp SetCustomerPriceResult)
        {
            this.SetCustomerPriceResult = SetCustomerPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetOrder", WrapperNamespace="http://nrsys.sk/ZTOS/Service/Types", IsWrapped=true)]
    public partial class SetOrderRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types")]
        public Medart.SK.Service.ZTOSAuth ZTOSAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Medart.SK.Service.Order ClientOrder;
        
        public SetOrderRequest()
        {
        }
        
        public SetOrderRequest(Medart.SK.Service.ZTOSAuth ZTOSAuth, Medart.SK.Service.Order ClientOrder)
        {
            this.ZTOSAuth = ZTOSAuth;
            this.ClientOrder = ClientOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetOrderResponse", WrapperNamespace="http://nrsys.sk/ZTOS/Service/Types", IsWrapped=true)]
    public partial class SetOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nrsys.sk/ZTOS/Service/Types", Order=0)]
        public Medart.SK.Service.SetOrderResp SetOrderResult;
        
        public SetOrderResponse()
        {
        }
        
        public SetOrderResponse(Medart.SK.Service.SetOrderResp SetOrderResult)
        {
            this.SetOrderResult = SetOrderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ZTOSServiceChannel : Medart.SK.Service.ZTOSService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ZTOSServiceClient : System.ServiceModel.ClientBase<Medart.SK.Service.ZTOSService>, Medart.SK.Service.ZTOSService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ZTOSServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ZTOSServiceClient.GetBindingForEndpoint(endpointConfiguration), ZTOSServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZTOSServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ZTOSServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZTOSServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ZTOSServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZTOSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Medart.SK.Service.GetClientsResponse> Medart.SK.Service.ZTOSService.GetClientsAsync(Medart.SK.Service.GetClientsRequest request)
        {
            return base.Channel.GetClientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Medart.SK.Service.GetClientsResponse> GetClientsAsync(Medart.SK.Service.ZTOSAuth ZTOSAuth)
        {
            Medart.SK.Service.GetClientsRequest inValue = new Medart.SK.Service.GetClientsRequest();
            inValue.ZTOSAuth = ZTOSAuth;
            return ((Medart.SK.Service.ZTOSService)(this)).GetClientsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Medart.SK.Service.GetProductsResponse> Medart.SK.Service.ZTOSService.GetProductsAsync(Medart.SK.Service.GetProductsRequest request)
        {
            return base.Channel.GetProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Medart.SK.Service.GetProductsResponse> GetProductsAsync(Medart.SK.Service.ZTOSAuth ZTOSAuth)
        {
            Medart.SK.Service.GetProductsRequest inValue = new Medart.SK.Service.GetProductsRequest();
            inValue.ZTOSAuth = ZTOSAuth;
            return ((Medart.SK.Service.ZTOSService)(this)).GetProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Medart.SK.Service.GetSalesResponse> Medart.SK.Service.ZTOSService.GetSalesAsync(Medart.SK.Service.GetSalesRequest request)
        {
            return base.Channel.GetSalesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Medart.SK.Service.GetSalesResponse> GetSalesAsync(Medart.SK.Service.ZTOSAuth ZTOSAuth, string DateFrom, string DateTo)
        {
            Medart.SK.Service.GetSalesRequest inValue = new Medart.SK.Service.GetSalesRequest();
            inValue.ZTOSAuth = ZTOSAuth;
            inValue.DateFrom = DateFrom;
            inValue.DateTo = DateTo;
            return ((Medart.SK.Service.ZTOSService)(this)).GetSalesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Medart.SK.Service.GetStocksResponse> Medart.SK.Service.ZTOSService.GetStocksAsync(Medart.SK.Service.GetStocksRequest request)
        {
            return base.Channel.GetStocksAsync(request);
        }
        
        public System.Threading.Tasks.Task<Medart.SK.Service.GetStocksResponse> GetStocksAsync(Medart.SK.Service.ZTOSAuth ZTOSAuth)
        {
            Medart.SK.Service.GetStocksRequest inValue = new Medart.SK.Service.GetStocksRequest();
            inValue.ZTOSAuth = ZTOSAuth;
            return ((Medart.SK.Service.ZTOSService)(this)).GetStocksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Medart.SK.Service.GetOrderConfirmationResponse> Medart.SK.Service.ZTOSService.GetOrderConfirmationAsync(Medart.SK.Service.GetOrderConfirmationRequest request)
        {
            return base.Channel.GetOrderConfirmationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Medart.SK.Service.GetOrderConfirmationResponse> GetOrderConfirmationAsync(Medart.SK.Service.ZTOSAuth ZTOSAuth, int ClientID, string ClientOrderID)
        {
            Medart.SK.Service.GetOrderConfirmationRequest inValue = new Medart.SK.Service.GetOrderConfirmationRequest();
            inValue.ZTOSAuth = ZTOSAuth;
            inValue.ClientID = ClientID;
            inValue.ClientOrderID = ClientOrderID;
            return ((Medart.SK.Service.ZTOSService)(this)).GetOrderConfirmationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Medart.SK.Service.SetCatalogPriceResponse> Medart.SK.Service.ZTOSService.SetCatalogPriceAsync(Medart.SK.Service.SetCatalogPriceRequest request)
        {
            return base.Channel.SetCatalogPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Medart.SK.Service.SetCatalogPriceResponse> SetCatalogPriceAsync(Medart.SK.Service.ZTOSAuth ZTOSAuth, Medart.SK.Service.CatalogPrice[] CatalogPrices)
        {
            Medart.SK.Service.SetCatalogPriceRequest inValue = new Medart.SK.Service.SetCatalogPriceRequest();
            inValue.ZTOSAuth = ZTOSAuth;
            inValue.CatalogPrices = CatalogPrices;
            return ((Medart.SK.Service.ZTOSService)(this)).SetCatalogPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Medart.SK.Service.SetCustomerPriceResponse> Medart.SK.Service.ZTOSService.SetCustomerPriceAsync(Medart.SK.Service.SetCustomerPriceRequest request)
        {
            return base.Channel.SetCustomerPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Medart.SK.Service.SetCustomerPriceResponse> SetCustomerPriceAsync(Medart.SK.Service.ZTOSAuth ZTOSAuth, Medart.SK.Service.CustomerPrice[] CustomerPrices)
        {
            Medart.SK.Service.SetCustomerPriceRequest inValue = new Medart.SK.Service.SetCustomerPriceRequest();
            inValue.ZTOSAuth = ZTOSAuth;
            inValue.CustomerPrices = CustomerPrices;
            return ((Medart.SK.Service.ZTOSService)(this)).SetCustomerPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Medart.SK.Service.SetOrderResponse> Medart.SK.Service.ZTOSService.SetOrderAsync(Medart.SK.Service.SetOrderRequest request)
        {
            return base.Channel.SetOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<Medart.SK.Service.SetOrderResponse> SetOrderAsync(Medart.SK.Service.ZTOSAuth ZTOSAuth, Medart.SK.Service.Order ClientOrder)
        {
            Medart.SK.Service.SetOrderRequest inValue = new Medart.SK.Service.SetOrderRequest();
            inValue.ZTOSAuth = ZTOSAuth;
            inValue.ClientOrder = ClientOrder;
            return ((Medart.SK.Service.ZTOSService)(this)).SetOrderAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZTOSService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;
                result.OpenTimeout = new TimeSpan(0, 10, 0);
                result.CloseTimeout = new TimeSpan(0, 10, 0);
                result.SendTimeout = new TimeSpan(0, 10, 0);
                result.ReceiveTimeout = new TimeSpan(0, 10, 0);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ZTOSService1))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZTOSService))
            {
                return new System.ServiceModel.EndpointAddress("https://objednavky.med-art.sk/ZTOS/ZTOSService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ZTOSService1))
            {
                return new System.ServiceModel.EndpointAddress("https://objednavky.med-art.sk/ZTOS/ZTOSService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ZTOSService,
            
            ZTOSService1,
        }
    }
}
