//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGVet.CZ.Service
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.modules.adamint.hs.cz/")]
    public partial class AdamintHSB2BException
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.modules.adamint.hs.cz/")]
    public partial class orderConfirmItemTO
    {
        
        private string batchNoField;
        
        private System.DateTime expirationField;
        
        private bool expirationFieldSpecified;
        
        private string lineIdField;
        
        private double priceField;
        
        private bool priceFieldSpecified;
        
        private int productIdField;
        
        private string productNameField;
        
        private int quantityField;
        
        private bool rebateField;
        
        private bool recordedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string batchNo
        {
            get
            {
                return this.batchNoField;
            }
            set
            {
                this.batchNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime expiration
        {
            get
            {
                return this.expirationField;
            }
            set
            {
                this.expirationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expirationSpecified
        {
            get
            {
                return this.expirationFieldSpecified;
            }
            set
            {
                this.expirationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string lineId
        {
            get
            {
                return this.lineIdField;
            }
            set
            {
                this.lineIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified
        {
            get
            {
                return this.priceFieldSpecified;
            }
            set
            {
                this.priceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string productName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool rebate
        {
            get
            {
                return this.rebateField;
            }
            set
            {
                this.rebateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool recorded
        {
            get
            {
                return this.recordedField;
            }
            set
            {
                this.recordedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.modules.adamint.hs.cz/")]
    public partial class orderConfirmTO
    {
        
        private string customerOrderIdField;
        
        private orderConfirmItemTO[] itemsField;
        
        private string noteField;
        
        private int orderIdField;
        
        private bool orderIdFieldSpecified;
        
        private string orderIdKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string customerOrderId
        {
            get
            {
                return this.customerOrderIdField;
            }
            set
            {
                this.customerOrderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public orderConfirmItemTO[] items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int orderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderIdSpecified
        {
            get
            {
                return this.orderIdFieldSpecified;
            }
            set
            {
                this.orderIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string orderIdKey
        {
            get
            {
                return this.orderIdKeyField;
            }
            set
            {
                this.orderIdKeyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://b2b.modules.adamint.hs.cz/", ConfigurationName="SGVet.CZ.Service.HSB2Bws")]
    public interface HSB2Bws
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/getOrderRequest", ReplyAction="http://b2b.modules.adamint.hs.cz/HSB2Bws/getOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SGVet.CZ.Service.AdamintHSB2BException), Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/getOrder/Fault/AdamintHSB2BException", Name="AdamintHSB2BException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.getOrderResponse> getOrderAsync(SGVet.CZ.Service.getOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/getSalesRequest", ReplyAction="http://b2b.modules.adamint.hs.cz/HSB2Bws/getSalesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SGVet.CZ.Service.AdamintHSB2BException), Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/getSales/Fault/AdamintHSB2BException", Name="AdamintHSB2BException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.getSalesResponse> getSalesAsync(SGVet.CZ.Service.getSalesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/getProductsRequest", ReplyAction="http://b2b.modules.adamint.hs.cz/HSB2Bws/getProductsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SGVet.CZ.Service.AdamintHSB2BException), Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/getProducts/Fault/AdamintHSB2BException", Name="AdamintHSB2BException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.getProductsResponse> getProductsAsync(SGVet.CZ.Service.getProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/getStocksRequest", ReplyAction="http://b2b.modules.adamint.hs.cz/HSB2Bws/getStocksResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SGVet.CZ.Service.AdamintHSB2BException), Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/getStocks/Fault/AdamintHSB2BException", Name="AdamintHSB2BException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.getStocksResponse> getStocksAsync(SGVet.CZ.Service.getStocksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/getClientDetailRequest", ReplyAction="http://b2b.modules.adamint.hs.cz/HSB2Bws/getClientDetailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SGVet.CZ.Service.AdamintHSB2BException), Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/getClientDetail/Fault/AdamintHSB2BExcept" +
            "ion", Name="AdamintHSB2BException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.getClientDetailResponse> getClientDetailAsync(SGVet.CZ.Service.getClientDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/getClientsRequest", ReplyAction="http://b2b.modules.adamint.hs.cz/HSB2Bws/getClientsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SGVet.CZ.Service.AdamintHSB2BException), Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/getClients/Fault/AdamintHSB2BException", Name="AdamintHSB2BException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.getClientsResponse> getClientsAsync(SGVet.CZ.Service.getClientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/setClientPricingRequest", ReplyAction="http://b2b.modules.adamint.hs.cz/HSB2Bws/setClientPricingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SGVet.CZ.Service.AdamintHSB2BException), Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/setClientPricing/Fault/AdamintHSB2BExcep" +
            "tion", Name="AdamintHSB2BException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.setClientPricingResponse> setClientPricingAsync(SGVet.CZ.Service.setClientPricingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/setCatalogPricesRequest", ReplyAction="http://b2b.modules.adamint.hs.cz/HSB2Bws/setCatalogPricesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SGVet.CZ.Service.AdamintHSB2BException), Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/setCatalogPrices/Fault/AdamintHSB2BExcep" +
            "tion", Name="AdamintHSB2BException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.setCatalogPricesResponse> setCatalogPricesAsync(SGVet.CZ.Service.setCatalogPricesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/putOrderRequest", ReplyAction="http://b2b.modules.adamint.hs.cz/HSB2Bws/putOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SGVet.CZ.Service.AdamintHSB2BException), Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/putOrder/Fault/AdamintHSB2BException", Name="AdamintHSB2BException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.putOrderResponse> putOrderAsync(SGVet.CZ.Service.putOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/getVersionRequest", ReplyAction="http://b2b.modules.adamint.hs.cz/HSB2Bws/getVersionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SGVet.CZ.Service.AdamintHSB2BException), Action="http://b2b.modules.adamint.hs.cz/HSB2Bws/getVersion/Fault/AdamintHSB2BException", Name="AdamintHSB2BException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.getVersionResponse> getVersionAsync(SGVet.CZ.Service.getVersionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrder", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class getOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.modules.adamint.hs.cz/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderIdKey;
        
        public getOrderRequest()
        {
        }
        
        public getOrderRequest(string orderIdKey)
        {
            this.orderIdKey = orderIdKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrderResponse", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class getOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.modules.adamint.hs.cz/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SGVet.CZ.Service.orderConfirmTO @return;
        
        public getOrderResponse()
        {
        }
        
        public getOrderResponse(SGVet.CZ.Service.orderConfirmTO @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.modules.adamint.hs.cz/")]
    public partial class salesDataTO
    {
        
        private string batchNoField;
        
        private string clientCityField;
        
        private string clientICField;
        
        private int clientIdField;
        
        private string clientKeyField;
        
        private string clientNameField;
        
        private string clientStreetField;
        
        private string clientZipField;
        
        private System.DateTime dateOfSaleField;
        
        private bool dateOfSaleFieldSpecified;
        
        private int orderIdField;
        
        private bool orderIdFieldSpecified;
        
        private double priceBaseField;
        
        private bool priceBaseFieldSpecified;
        
        private int productIdField;
        
        private int quantityField;
        
        private bool rabatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string batchNo
        {
            get
            {
                return this.batchNoField;
            }
            set
            {
                this.batchNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clientCity
        {
            get
            {
                return this.clientCityField;
            }
            set
            {
                this.clientCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string clientIC
        {
            get
            {
                return this.clientICField;
            }
            set
            {
                this.clientICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int clientId
        {
            get
            {
                return this.clientIdField;
            }
            set
            {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string clientKey
        {
            get
            {
                return this.clientKeyField;
            }
            set
            {
                this.clientKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string clientName
        {
            get
            {
                return this.clientNameField;
            }
            set
            {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string clientStreet
        {
            get
            {
                return this.clientStreetField;
            }
            set
            {
                this.clientStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string clientZip
        {
            get
            {
                return this.clientZipField;
            }
            set
            {
                this.clientZipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime dateOfSale
        {
            get
            {
                return this.dateOfSaleField;
            }
            set
            {
                this.dateOfSaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateOfSaleSpecified
        {
            get
            {
                return this.dateOfSaleFieldSpecified;
            }
            set
            {
                this.dateOfSaleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int orderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderIdSpecified
        {
            get
            {
                return this.orderIdFieldSpecified;
            }
            set
            {
                this.orderIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double priceBase
        {
            get
            {
                return this.priceBaseField;
            }
            set
            {
                this.priceBaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceBaseSpecified
        {
            get
            {
                return this.priceBaseFieldSpecified;
            }
            set
            {
                this.priceBaseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public bool rabat
        {
            get
            {
                return this.rabatField;
            }
            set
            {
                this.rabatField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSales", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class getSalesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.modules.adamint.hs.cz/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.modules.adamint.hs.cz/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dateTo;
        
        public getSalesRequest()
        {
        }
        
        public getSalesRequest(System.DateTime dateFrom, System.DateTime dateTo)
        {
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSalesResponse", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class getSalesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.modules.adamint.hs.cz/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SGVet.CZ.Service.salesDataTO[] @return;
        
        public getSalesResponse()
        {
        }
        
        public getSalesResponse(SGVet.CZ.Service.salesDataTO[] @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.modules.adamint.hs.cz/")]
    public partial class productTO
    {
        
        private double catalogPriceField;
        
        private bool catalogPriceFieldSpecified;
        
        private bool finishedField;
        
        private string nameField;
        
        private string pdkIdField;
        
        private int productIdField;
        
        private bool productIdFieldSpecified;
        
        private string productIdKeyField;
        
        private string supplierIdField;
        
        private double vATField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double catalogPrice
        {
            get
            {
                return this.catalogPriceField;
            }
            set
            {
                this.catalogPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool catalogPriceSpecified
        {
            get
            {
                return this.catalogPriceFieldSpecified;
            }
            set
            {
                this.catalogPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool finished
        {
            get
            {
                return this.finishedField;
            }
            set
            {
                this.finishedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string pdkId
        {
            get
            {
                return this.pdkIdField;
            }
            set
            {
                this.pdkIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productIdSpecified
        {
            get
            {
                return this.productIdFieldSpecified;
            }
            set
            {
                this.productIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string productIdKey
        {
            get
            {
                return this.productIdKeyField;
            }
            set
            {
                this.productIdKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string supplierId
        {
            get
            {
                return this.supplierIdField;
            }
            set
            {
                this.supplierIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double VAT
        {
            get
            {
                return this.vATField;
            }
            set
            {
                this.vATField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProducts", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class getProductsRequest
    {
        
        public getProductsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductsResponse", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class getProductsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.modules.adamint.hs.cz/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SGVet.CZ.Service.productTO[] @return;
        
        public getProductsResponse()
        {
        }
        
        public getProductsResponse(SGVet.CZ.Service.productTO[] @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.modules.adamint.hs.cz/")]
    public partial class stockTO
    {
        
        private int batchIdField;
        
        private bool batchIdFieldSpecified;
        
        private string batchNoField;
        
        private System.DateTime expirationField;
        
        private bool expirationFieldSpecified;
        
        private int productIdField;
        
        private bool productIdFieldSpecified;
        
        private int stockLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int batchId
        {
            get
            {
                return this.batchIdField;
            }
            set
            {
                this.batchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool batchIdSpecified
        {
            get
            {
                return this.batchIdFieldSpecified;
            }
            set
            {
                this.batchIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string batchNo
        {
            get
            {
                return this.batchNoField;
            }
            set
            {
                this.batchNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime expiration
        {
            get
            {
                return this.expirationField;
            }
            set
            {
                this.expirationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expirationSpecified
        {
            get
            {
                return this.expirationFieldSpecified;
            }
            set
            {
                this.expirationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productIdSpecified
        {
            get
            {
                return this.productIdFieldSpecified;
            }
            set
            {
                this.productIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int stockLevel
        {
            get
            {
                return this.stockLevelField;
            }
            set
            {
                this.stockLevelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStocks", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class getStocksRequest
    {
        
        public getStocksRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStocksResponse", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class getStocksResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.modules.adamint.hs.cz/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SGVet.CZ.Service.stockTO[] @return;
        
        public getStocksResponse()
        {
        }
        
        public getStocksResponse(SGVet.CZ.Service.stockTO[] @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.modules.adamint.hs.cz/")]
    public partial class clientDetailTO : clientBaseTO
    {
        
        private clientPriceTO[] customPricesField;
        
        private clientDeliveryAddressTO[] deliveryAddressesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customPrices", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public clientPriceTO[] customPrices
        {
            get
            {
                return this.customPricesField;
            }
            set
            {
                this.customPricesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deliveryAddresses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public clientDeliveryAddressTO[] deliveryAddresses
        {
            get
            {
                return this.deliveryAddressesField;
            }
            set
            {
                this.deliveryAddressesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.modules.adamint.hs.cz/")]
    public partial class clientPriceTO
    {
        
        private double priceField;
        
        private bool priceFieldSpecified;
        
        private int productIdField;
        
        private bool productIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified
        {
            get
            {
                return this.priceFieldSpecified;
            }
            set
            {
                this.priceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productIdSpecified
        {
            get
            {
                return this.productIdFieldSpecified;
            }
            set
            {
                this.productIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.modules.adamint.hs.cz/")]
    public partial class clientDeliveryAddressTO
    {
        
        private int clientDeliveryAddressIdField;
        
        private bool clientDeliveryAddressIdFieldSpecified;
        
        private string deliveryCityField;
        
        private string deliveryNameField;
        
        private string deliveryStreetField;
        
        private string deliveryZipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int clientDeliveryAddressId
        {
            get
            {
                return this.clientDeliveryAddressIdField;
            }
            set
            {
                this.clientDeliveryAddressIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clientDeliveryAddressIdSpecified
        {
            get
            {
                return this.clientDeliveryAddressIdFieldSpecified;
            }
            set
            {
                this.clientDeliveryAddressIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string deliveryCity
        {
            get
            {
                return this.deliveryCityField;
            }
            set
            {
                this.deliveryCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string deliveryName
        {
            get
            {
                return this.deliveryNameField;
            }
            set
            {
                this.deliveryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string deliveryStreet
        {
            get
            {
                return this.deliveryStreetField;
            }
            set
            {
                this.deliveryStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string deliveryZip
        {
            get
            {
                return this.deliveryZipField;
            }
            set
            {
                this.deliveryZipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clientTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clientDetailTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.modules.adamint.hs.cz/")]
    public abstract partial class clientBaseTO
    {
        
        private string cityField;
        
        private int clientIdField;
        
        private bool clientIdFieldSpecified;
        
        private string clientIdKeyField;
        
        private int clientMasterIdField;
        
        private bool clientMasterIdFieldSpecified;
        
        private string clientMasterIdKeyField;
        
        private string emailField;
        
        private bool finishedField;
        
        private string icField;
        
        private string nameField;
        
        private bool pricelessField;
        
        private string streetField;
        
        private string zipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int clientId
        {
            get
            {
                return this.clientIdField;
            }
            set
            {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clientIdSpecified
        {
            get
            {
                return this.clientIdFieldSpecified;
            }
            set
            {
                this.clientIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string clientIdKey
        {
            get
            {
                return this.clientIdKeyField;
            }
            set
            {
                this.clientIdKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int clientMasterId
        {
            get
            {
                return this.clientMasterIdField;
            }
            set
            {
                this.clientMasterIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clientMasterIdSpecified
        {
            get
            {
                return this.clientMasterIdFieldSpecified;
            }
            set
            {
                this.clientMasterIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string clientMasterIdKey
        {
            get
            {
                return this.clientMasterIdKeyField;
            }
            set
            {
                this.clientMasterIdKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool finished
        {
            get
            {
                return this.finishedField;
            }
            set
            {
                this.finishedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string IC
        {
            get
            {
                return this.icField;
            }
            set
            {
                this.icField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool priceless
        {
            get
            {
                return this.pricelessField;
            }
            set
            {
                this.pricelessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.modules.adamint.hs.cz/")]
    public partial class clientTO : clientBaseTO
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClientDetail", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class getClientDetailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.modules.adamint.hs.cz/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientIdKey;
        
        public getClientDetailRequest()
        {
        }
        
        public getClientDetailRequest(string clientIdKey)
        {
            this.clientIdKey = clientIdKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClientDetailResponse", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class getClientDetailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.modules.adamint.hs.cz/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SGVet.CZ.Service.clientDetailTO @return;
        
        public getClientDetailResponse()
        {
        }
        
        public getClientDetailResponse(SGVet.CZ.Service.clientDetailTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClients", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class getClientsRequest
    {
        
        public getClientsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClientsResponse", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class getClientsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.modules.adamint.hs.cz/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SGVet.CZ.Service.clientTO[] @return;
        
        public getClientsResponse()
        {
        }
        
        public getClientsResponse(SGVet.CZ.Service.clientTO[] @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.modules.adamint.hs.cz/")]
    public partial class clientPricingRequestTO
    {
        
        private string clientIdKeyField;
        
        private productPriceTO[] productPricesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string clientIdKey
        {
            get
            {
                return this.clientIdKeyField;
            }
            set
            {
                this.clientIdKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("productPrices", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public productPriceTO[] productPrices
        {
            get
            {
                return this.productPricesField;
            }
            set
            {
                this.productPricesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.modules.adamint.hs.cz/")]
    public partial class productPriceTO
    {
        
        private double priceField;
        
        private bool priceFieldSpecified;
        
        private string productIdKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified
        {
            get
            {
                return this.priceFieldSpecified;
            }
            set
            {
                this.priceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string productIdKey
        {
            get
            {
                return this.productIdKeyField;
            }
            set
            {
                this.productIdKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setClientPricing", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class setClientPricingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.modules.adamint.hs.cz/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ClientPricingList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SGVet.CZ.Service.clientPricingRequestTO[] ClientPricingList;
        
        public setClientPricingRequest()
        {
        }
        
        public setClientPricingRequest(SGVet.CZ.Service.clientPricingRequestTO[] ClientPricingList)
        {
            this.ClientPricingList = ClientPricingList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setClientPricingResponse", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class setClientPricingResponse
    {
        
        public setClientPricingResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCatalogPrices", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class setCatalogPricesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.modules.adamint.hs.cz/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CatalogPriceList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SGVet.CZ.Service.productPriceTO[] CatalogPriceList;
        
        public setCatalogPricesRequest()
        {
        }
        
        public setCatalogPricesRequest(SGVet.CZ.Service.productPriceTO[] CatalogPriceList)
        {
            this.CatalogPriceList = CatalogPriceList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCatalogPricesResponse", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class setCatalogPricesResponse
    {
        
        public setCatalogPricesResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.modules.adamint.hs.cz/")]
    public partial class orderRequestTO
    {
        
        private string clientIdKeyField;
        
        private bool collectField;
        
        private string customerOrderIdField;
        
        private orderRequestItemTO[] itemsField;
        
        private string notesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string clientIdKey
        {
            get
            {
                return this.clientIdKeyField;
            }
            set
            {
                this.clientIdKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool collect
        {
            get
            {
                return this.collectField;
            }
            set
            {
                this.collectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string customerOrderId
        {
            get
            {
                return this.customerOrderIdField;
            }
            set
            {
                this.customerOrderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public orderRequestItemTO[] items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.modules.adamint.hs.cz/")]
    public partial class orderRequestItemTO
    {
        
        private bool bookField;
        
        private double customPriceField;
        
        private bool customPriceFieldSpecified;
        
        private string productIdKeyField;
        
        private int quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool book
        {
            get
            {
                return this.bookField;
            }
            set
            {
                this.bookField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double customPrice
        {
            get
            {
                return this.customPriceField;
            }
            set
            {
                this.customPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool customPriceSpecified
        {
            get
            {
                return this.customPriceFieldSpecified;
            }
            set
            {
                this.customPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string productIdKey
        {
            get
            {
                return this.productIdKeyField;
            }
            set
            {
                this.productIdKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="putOrder", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class putOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.modules.adamint.hs.cz/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SGVet.CZ.Service.orderRequestTO Order;
        
        public putOrderRequest()
        {
        }
        
        public putOrderRequest(SGVet.CZ.Service.orderRequestTO Order)
        {
            this.Order = Order;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="putOrderResponse", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class putOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.modules.adamint.hs.cz/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SGVet.CZ.Service.orderConfirmTO @return;
        
        public putOrderResponse()
        {
        }
        
        public putOrderResponse(SGVet.CZ.Service.orderConfirmTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersion", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class getVersionRequest
    {
        
        public getVersionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersionResponse", WrapperNamespace="http://b2b.modules.adamint.hs.cz/", IsWrapped=true)]
    public partial class getVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.modules.adamint.hs.cz/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getVersionResponse()
        {
        }
        
        public getVersionResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface HSB2BwsChannel : SGVet.CZ.Service.HSB2Bws, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class HSB2BwsClient : System.ServiceModel.ClientBase<SGVet.CZ.Service.HSB2Bws>, SGVet.CZ.Service.HSB2Bws
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HSB2BwsClient() : 
                base(HSB2BwsClient.GetDefaultBinding(), HSB2BwsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.HSB2BwsPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HSB2BwsClient(EndpointConfiguration endpointConfiguration) : 
                base(HSB2BwsClient.GetBindingForEndpoint(endpointConfiguration), HSB2BwsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HSB2BwsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HSB2BwsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HSB2BwsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HSB2BwsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HSB2BwsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.getOrderResponse> SGVet.CZ.Service.HSB2Bws.getOrderAsync(SGVet.CZ.Service.getOrderRequest request)
        {
            return base.Channel.getOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<SGVet.CZ.Service.getOrderResponse> getOrderAsync(string orderIdKey)
        {
            SGVet.CZ.Service.getOrderRequest inValue = new SGVet.CZ.Service.getOrderRequest();
            inValue.orderIdKey = orderIdKey;
            return ((SGVet.CZ.Service.HSB2Bws)(this)).getOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.getSalesResponse> SGVet.CZ.Service.HSB2Bws.getSalesAsync(SGVet.CZ.Service.getSalesRequest request)
        {
            return base.Channel.getSalesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SGVet.CZ.Service.getSalesResponse> getSalesAsync(System.DateTime dateFrom, System.DateTime dateTo)
        {
            SGVet.CZ.Service.getSalesRequest inValue = new SGVet.CZ.Service.getSalesRequest();
            inValue.dateFrom = dateFrom;
            inValue.dateTo = dateTo;
            return ((SGVet.CZ.Service.HSB2Bws)(this)).getSalesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.getProductsResponse> SGVet.CZ.Service.HSB2Bws.getProductsAsync(SGVet.CZ.Service.getProductsRequest request)
        {
            return base.Channel.getProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SGVet.CZ.Service.getProductsResponse> getProductsAsync()
        {
            SGVet.CZ.Service.getProductsRequest inValue = new SGVet.CZ.Service.getProductsRequest();
            return ((SGVet.CZ.Service.HSB2Bws)(this)).getProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.getStocksResponse> SGVet.CZ.Service.HSB2Bws.getStocksAsync(SGVet.CZ.Service.getStocksRequest request)
        {
            return base.Channel.getStocksAsync(request);
        }
        
        public System.Threading.Tasks.Task<SGVet.CZ.Service.getStocksResponse> getStocksAsync()
        {
            SGVet.CZ.Service.getStocksRequest inValue = new SGVet.CZ.Service.getStocksRequest();
            return ((SGVet.CZ.Service.HSB2Bws)(this)).getStocksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.getClientDetailResponse> SGVet.CZ.Service.HSB2Bws.getClientDetailAsync(SGVet.CZ.Service.getClientDetailRequest request)
        {
            return base.Channel.getClientDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<SGVet.CZ.Service.getClientDetailResponse> getClientDetailAsync(string clientIdKey)
        {
            SGVet.CZ.Service.getClientDetailRequest inValue = new SGVet.CZ.Service.getClientDetailRequest();
            inValue.clientIdKey = clientIdKey;
            return ((SGVet.CZ.Service.HSB2Bws)(this)).getClientDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.getClientsResponse> SGVet.CZ.Service.HSB2Bws.getClientsAsync(SGVet.CZ.Service.getClientsRequest request)
        {
            return base.Channel.getClientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SGVet.CZ.Service.getClientsResponse> getClientsAsync()
        {
            SGVet.CZ.Service.getClientsRequest inValue = new SGVet.CZ.Service.getClientsRequest();
            return ((SGVet.CZ.Service.HSB2Bws)(this)).getClientsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.setClientPricingResponse> SGVet.CZ.Service.HSB2Bws.setClientPricingAsync(SGVet.CZ.Service.setClientPricingRequest request)
        {
            return base.Channel.setClientPricingAsync(request);
        }
        
        public System.Threading.Tasks.Task<SGVet.CZ.Service.setClientPricingResponse> setClientPricingAsync(SGVet.CZ.Service.clientPricingRequestTO[] ClientPricingList)
        {
            SGVet.CZ.Service.setClientPricingRequest inValue = new SGVet.CZ.Service.setClientPricingRequest();
            inValue.ClientPricingList = ClientPricingList;
            return ((SGVet.CZ.Service.HSB2Bws)(this)).setClientPricingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.setCatalogPricesResponse> SGVet.CZ.Service.HSB2Bws.setCatalogPricesAsync(SGVet.CZ.Service.setCatalogPricesRequest request)
        {
            return base.Channel.setCatalogPricesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SGVet.CZ.Service.setCatalogPricesResponse> setCatalogPricesAsync(SGVet.CZ.Service.productPriceTO[] CatalogPriceList)
        {
            SGVet.CZ.Service.setCatalogPricesRequest inValue = new SGVet.CZ.Service.setCatalogPricesRequest();
            inValue.CatalogPriceList = CatalogPriceList;
            return ((SGVet.CZ.Service.HSB2Bws)(this)).setCatalogPricesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.putOrderResponse> SGVet.CZ.Service.HSB2Bws.putOrderAsync(SGVet.CZ.Service.putOrderRequest request)
        {
            return base.Channel.putOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<SGVet.CZ.Service.putOrderResponse> putOrderAsync(SGVet.CZ.Service.orderRequestTO Order)
        {
            SGVet.CZ.Service.putOrderRequest inValue = new SGVet.CZ.Service.putOrderRequest();
            inValue.Order = Order;
            return ((SGVet.CZ.Service.HSB2Bws)(this)).putOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SGVet.CZ.Service.getVersionResponse> SGVet.CZ.Service.HSB2Bws.getVersionAsync(SGVet.CZ.Service.getVersionRequest request)
        {
            return base.Channel.getVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SGVet.CZ.Service.getVersionResponse> getVersionAsync()
        {
            SGVet.CZ.Service.getVersionRequest inValue = new SGVet.CZ.Service.getVersionRequest();
            return ((SGVet.CZ.Service.HSB2Bws)(this)).getVersionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HSB2BwsPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;
                result.OpenTimeout = new TimeSpan(0, 10, 0);
                result.CloseTimeout = new TimeSpan(0, 10, 0);
                result.SendTimeout = new TimeSpan(0, 10, 0);
                result.ReceiveTimeout = new TimeSpan(0, 10, 0);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HSB2BwsPort))
            {
                return new System.ServiceModel.EndpointAddress("https://eshop.sgvet.cz/ws/b2b");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HSB2BwsClient.GetBindingForEndpoint(EndpointConfiguration.HSB2BwsPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HSB2BwsClient.GetEndpointAddress(EndpointConfiguration.HSB2BwsPort);
        }
        
        public enum EndpointConfiguration
        {
            
            HSB2BwsPort,
        }
    }
}
